/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Assignment;

import java.io.File;
import java.io.IOException;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

/**
 *
 * @author sarahsyazwina
 */
public class Panel extends javax.swing.JFrame {

    /** Creates new form Panel */
    public Panel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        panel = new javax.swing.JPanel();
        staticDisp = new javax.swing.JLabel();
        levelDisp = new javax.swing.JLabel();
        doorStatic = new javax.swing.JLabel();
        line = new javax.swing.JSeparator();
        doorDisp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Elevator Display");
        setAlwaysOnTop(true);
        setResizable(false);

        panel.setBackground(new java.awt.Color(153, 153, 153));

        staticDisp.setFont(new java.awt.Font("Andale Mono", 0, 24)); // NOI18N
        staticDisp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        staticDisp.setText("ELEVATOR ON LEVEL");

        levelDisp.setFont(new java.awt.Font("Andale Mono", 0, 24)); // NOI18N
        levelDisp.setForeground(new java.awt.Color(255, 255, 255));
        levelDisp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        levelDisp.setText("G");

        doorStatic.setFont(new java.awt.Font("Andale Mono", 0, 24)); // NOI18N
        doorStatic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doorStatic.setText("DOORS ARE");

        line.setForeground(new java.awt.Color(102, 102, 102));
        line.setOrientation(javax.swing.SwingConstants.VERTICAL);

        doorDisp.setFont(new java.awt.Font("Andale Mono", 0, 24)); // NOI18N
        doorDisp.setForeground(new java.awt.Color(255, 255, 255));
        doorDisp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        doorDisp.setText("CLOSED");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addComponent(staticDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(levelDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(line, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(doorStatic, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doorDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(staticDisp, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addComponent(levelDisp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(doorStatic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(line)
                .addContainerGap())
            .addComponent(doorDisp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Panel().setVisible(true);
        });
    }
    
    public void doorDisp(String string){
        doorDisp.setText(string);
        doorDisp.repaint();
        setVisible(true);
    }
    
    public void levelDisp(String string){
        levelDisp.setText(string);
        levelDisp.repaint();
        setVisible(true);
    }
    
    public void playSound(String clip){
        try {
            AudioInputStream a = AudioSystem.getAudioInputStream(new File(clip).getAbsoluteFile());
            Clip c = AudioSystem.getClip();
            c.open(a);
            c.start();
        } catch (LineUnavailableException | IOException | UnsupportedAudioFileException ex) {
            System.out.println("Problem playing audio.");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel doorDisp;
    public javax.swing.JLabel doorStatic;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel levelDisp;
    public javax.swing.JSeparator line;
    public javax.swing.JPanel panel;
    public javax.swing.JLabel staticDisp;
    // End of variables declaration//GEN-END:variables

}
